- apiVersion: v1
  kind: Service
  metadata:
    namespace: infra
    name: kibana
    labels:
      app: kibana
      name: kibana
      namespace: infra
  spec:
    selector:
      app: kibana
    ports:
      - name: kibana
        port: 5601
        targetPort: 5601
        protocol: TCP
