name = "heapster.kube-system"
image = "gcr.io/google_containers/heapster-amd64:v1.3.0"
command = "/heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://influxdb.data:8086"
labels = "task=monitoring;k8s-app=heapster"

[scale]
  containers = 1
  ram = "> 50 Mi < 200 Mi"
  cpu = "> 10% < 20%"

[security]
  account = "heapster"
  role = "ClusterRole;system:heapster"

[service]
  labels = "task=monitoring;kubernetes.io/cluster-service='true';kubernetes.io/name=Heapster"
