apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns
  name: two
  labels:
    name: two
    namespace: ns
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: two
  template:
    metadata:
      labels:
        app: two
        name: two
        namespace: ns
    spec:
      containers:
        - name: two
          image: 'repo/two:latest'
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 500m
