[kube-system.heapster]
  order = 0
  [kube-system.heapster.scale]
    small = "+0"
    medium = "+1"
    large = "+2"


[infra.create-cert]
  order = 10

[data.chronograf]
  order = 50
  [data.chronograf.scale]
    small = "+0"
[data.influxdb]
  order = 50
  [data.influxdb.scale]
    small = "+0"
[data.kapacitor]
  order = 50
  [data.kapacitor.scale]
    small = "+0"

[infra.proxy]
  order = 100
  [infra.proxy.scale]
    small = "+0"
    medium = "+1"
    large = "+2"

[configuration.infra.config]
  test = "hello"
  empty = ""

[imagePullSecret.repo-creds]
  namespaces = [ "data" ]
  registry = "quay.io"
  repositories = [ "influxdb" ]
  username = "service-account-name"
  password = "my-secret-password-no-one-knows"
