[test.basicPod]
order=0

#[test.basicNode]
#order=0

#[test.clusterDefault]
#order=0
#
#[test.overrideToEmpty]
#order=0
#
#[test.raw]
#order=0
#
#[test.self]
#order=0
#
#[test.badWeights]
#order=0
#
#[test.badLabels]
#order=0
#
#[test.badNodeWeight]
#order=0
#
#[test.badNodeNegativeWeight]
#order=0
