name = "role-name.my-namespace"

[security]
  account = "some-account"
  role = "Role;some-role"
  [[security.rules]]
    verbs = [ "create", "get", "update", "delete" ]
    resources = [ "secrets" ]
