[<%= namespace %>.elasticsearch]
  order = <%= elk.start %>
[<%= namespace %>.kibana]
  order = <%= elk.start + 1 %>
[<%= namespace %>.logstash]
  order = <%= elk.start + 1 %>
[<%= namespace %>.<%= filebeat %>]
  order = <%= elk.start % 1 %>
