[<%= namespace %>.elasticsearch]
  order = <%= elk_start %>
[<%= namespace %>.kibana]
  order = <%= elk_start + 1 %>
[<%= namespace %>.logstash]
  order = <%= elk_start + 1 %>
[<%= namespace %>.<%= filebeat %>]
  order = <%= elk_start % 1 %>
