apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns
  name: one
  labels:
    name: one
    namespace: ns
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: one
  template:
    metadata:
      labels:
        app: one
        name: one
        namespace: ns
    spec:
      containers:
        - name: one
          image: 'repo/one:latest'
          resources:
            requests:
              memory: 250Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 100m
